spring:
  datasource:
    url: jdbc:h2:mem:demodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate: ddl-auto
  h2:
    console:
      enabled: true
      path: /h2-ui
  application:
    name: DEMO-RESTFUL-API

#============================================================================
# LOGGER
#============================================================================
logging:
  config: classpath:logback-spring.xml
  file:
    path: /
    name: restful-api.log
  level:
    com:
      saptarga:
        example:
          demo: DEBUG
    org.springframework.cache: trace

#============================================================================
# LOG FILE
#============================================================================
log:
  enabled: false
  file:
    path: /tmp/restful-api.log

#============================================================================
# REST CLIENT
#============================================================================
rest:
  raja-ongkir:
    base-path: https://api.rajaongkir.com/starter
    key: a2ccef52deeb31eef91723d90f5883e0

feign:
  client:
    config:
      default:
        loggerLevel: full